---
title: "DPPP"
author: "Mushaphi DP (1422504)"
date: "2023-11-04"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(geoR)
points(sic.100, borders = sic.borders, col = "blue")
points(sic.367, borders = sic.borders, col = "red", add = TRUE)

```
```{r}
library(geoR)
plot.geodata(sic.100,bor=sic.borders)
```

```{r}
library(geoR)
library(fields)
vario.b<- variog(sic.100,option =c ("bin", "cloud", "smooth"),
bin.cloud=TRUE)
plot(vario.b)
```
```{r}
vario.c <- variog(sic.100, op="cloud")
bplot.xy(vario.c$u,vario.c$v, breaks=vario.b$u,col="grey80",
lwd=2,cex=0.1,outline=FALSE)
plot(vario.c)
```

```{r}
library(geoR)
vario.ex<- variog(sic.100, bin.cloud=TRUE)
plot(vario.ex)
```
```{r}
library(geoR)
par(mfrow = c(2, 2), mar = c(5, 4, 4, 2) + 0.1, mgp = c(2, 1, 0))
vario4<-variog4(sic.100)
plot(vario4,same= FALSE)
```
```{r}
library(geoR)
vario.ex<- variog(sic.100,option="bin")
vario.sphe<-(variofit(vario.ex,cov.model= "spher",
ini.cov.pars=c(15000,200)))
par(mfrow=c(2,2), mar=c(3,3,1,1), mgp =c (2,1,0))
plot(vario.ex,main="Spherical")
lines.variomodel(cov.model="sphe",cov.pars=c(15000,100),
nug=0,max.dist=350)

plot(vario.ex,main="Exponential")
lines.variomodel(cov.model="exp",cov.pars=c(15000,100),
nug=0,max.dist=350)

plot(vario.ex, main = "Exponential with Nugget")
lines.variomodel(cov.model = "exp", cov.pars = c(15000, 100), nug = 0.1, max.dist = 350)

plot(vario.ex, main = "Gaussian")
lines.variomodel(cov.model = "gaus", cov.pars = c(15000, 100), nug = 0, max.dist = 350)
```



```{r}
 library(geoR)
vario.ex<- variog(sic.100, bin.cloud=TRUE)
plot(vario.ex,main="spherical")
lines.variomodel(cov.model="spher",cov.pars=c(15000,50),
nug=0,max.dist=300)              
```
```{r}
library(geoR)
pred.grid <- expand.grid(seq(0,350, l=51),seq (0,220, l=51))
custom_palette <- colorRampPalette(c("green", "yellow", "orange", "red"), space = "rgb")
kc<- krige.conv(sic.100, loc = pred.grid,krige=krige.control(cov.model="spherical",cov.pars=c(15000,50)))
image(kc, loc = pred.grid, col = custom_palette(20), xlab = "CoordX", ylab = "CoordY", borders = sic.borders, main = "Estimation")
krige.var <- kc$krige.var
image(kc, krige.var, loc = pred.grid, col = custom_palette(20), xlab = "Coord X", ylab = "Coord Y", borders = sic.borders, main = "Kriging Variance")
```
```{r}
library(geoR)
kc1<- krige.conv(sic.100, loc = sic.100$coords,
krige=krige.control(cov.model="spherical",cov.pars=c(16000,47)))
kc2<- krige.conv(sic.100, loc = sic.367$coords,
krige=krige.control(cov.model="spherical",cov.pars=c(16000,47)))
plot(sic.100$data,kc1$predict,xlab="Observed",ylab="Estimated",
main="Control sample")
abline(a=0,b=1,col="red")
plot(sic.367$data, kc2$predict, xlab = "Observed", ylab = "Estimated", main = "Control")
abline(a = 0, b = 1, col = "red")
```
```{r}
library(geoR)
plot.geodata(sic.100,bor=sic.borders,lambda=0.5)
```

```{r}
library(geoR)
vario.ext<- variog(sic.100,option="bin",lambda=0.5)
plot(vario.ext)
lines.variomodel(cov.m = "mat",cov.p =c (105, 36), nug = 6.9,
max.dist = 300,kappa = 1, lty = 1)
```

```{r}
library(geoR)
kct<- krige.conv(sic.100, loc = pred.grid,
krige=krige.control(cov.model="matern",cov.pars=c(105, 36),
kappa=1,nugget=6.9,lambda=0.5))
pred.grid <- expand.grid(seq(0,350, l=51),seq (0,220, l=51))
new_palette <- colorRampPalette(c("green", "yellow", "orange", "red"))
image(kct, loc = pred.grid, col = new_palette(20), xlab = "Coord X", ylab = "Coord Y", borders = sic.borders, main = "Estimation")
krige.var1 <- kct$krige.var
image(kct, krige.var1, loc = pred.grid, col = new_palette(20), xlab = "Coord X", ylab = "Coord Y", borders = sic.borders, main = "Kriging Variance")
```

```{r}
library(geoR)
kct1 <- krige.conv(
  sic.100,
  loc = sic.100$coords,
  krige = krige.control(
    cov.model = "spherical",
    cov.pars = c(16000, 47),
    kappa = 1,
    nugget = 6.9,
    lambda = 0.5
  )
)

kct2 <- krige.conv(
  sic.100,
  loc = sic.367$coords,
  krige = krige.control(
    cov.model = "spherical",
    cov.pars = c(16000, 47),
    kappa = 1,
    nugget = 6.9,
    lambda = 0.5
  )
)

par(mfrow = c(1, 2))
plot(sic.100$data, kct1$predict, xlab = "Observed", ylab = "Estimated", main = "Sample")
abline(a = 0, b = 1, col  = "red")
plot(sic.367$data, kct2$predict, xlab = "Observed", ylab = "Estimated", main = "Control sample")
abline(a = 5, b = 10, col = "red")

```


```{r}
library(geoR)
kct1 <- krige.conv(
  sic.100,
  loc = sic.100$coords,
  krige = krige.control(
    cov.model = "spherical",
    cov.pars = c(16000, 47),
    kappa = 1,
    nugget = 6.9,
    lambda = 0.5
  )
)

kct2 <- krige.conv(
  sic.100,
  loc = sic.367$coords,
  krige = krige.control(
    cov.model = "spherical",
    cov.pars = c(16000, 47),
    kappa = 1,
    nugget = 6.9,
    lambda = 0.5
  )
)

par(mfrow = c(1, 2))
plot(sic.100$data, kct1$predict, xlab = "Observed", ylab = "Estimated", main = "Sample")
abline(a = 0, b = 1, col  = "red")
plot(sic.367$data, kct2$predict, xlab = "Observed", ylab = "Estimated", main = "Control sample")
abline(a = 0, b = 10, col = "red")

```










